### ISSUE TITLE
golang-example fails to fetch and dependencies.

### ISSUE THREAD

**Issue by mlarrousse** [jfrog/project-examples#128]
I'm following the steps in golang-example, have set up my repositories, vgo and the jfrog CLI, but when I run vgo build in the project directory I get the following:

```
mary@marys-mbp:~/go/src/github.com/jfrog/project-examples/golang-example/hello$ jfrog rt go build --no-registry
[Info] Using vgo: go version go1.10.2 darwin/amd64 vgo:2018-02-20.1

vgo: rsc.io/quote v1.5.2: unexpected status (https://<user>:<pw>@cyrusbio.jfrog.io/cyrusbio/api/go/go-virtual/rsc.io/quote/@v/v1.5.2.mod): 404 Not Found
vgo: unexpected status (https://<user>:<pw>@cyrusbio.jfrog.io/cyrusbio/api/go/go-virtual/rsc.io/quote/@v/v1.5.2.mod): 404 Not Found
{
  "status": "failure",
  "totals": {
    "success": 0,
    "failure": 1
  }
}
[Error] exit status 1
```

Is there something missing from the documentation?

**Comment by eyalbe4** [comment]
@mlarrousse,
Can you please let us know if you get the same error with the latest vgo release? I suspect that the issue is causred since you're using an old vgo version.

**Comment by mlarrousse** [comment]
I've installed vgo via `go get -u golang.org/x/vgo` today.

The version string that prints out is just a constant: https://github.com/golang/vgo/blob/b39cea3cb5353f4fc7f08919d32a0006ea3ed62a/vendor/cmd/go/internal/version/version.go#L16

**Comment by AlexeiVainshtein** [comment]
Hi @mlarrousse 

When using the --no-registry flag means that Vgo uses the default configured registry. Vgo checks if there is an environment variable GOPROXY and if there is, Vgo uses the value of this environment proxy to download the dependencies from. 
From your snippet that you have send us it seems  that you are still going to your Artifactory server: https://<user>:<pw>@cyrusbio.jfrog.io/cyrusbio
Could it be that you have this environment variable configured and therefore Vgo goes to this URL?
Also, can you please run vgo build and send us the output? 

Thanks,

**Comment by mlarrousse** [comment]
Thank you! Setting GOPROXY to "" and running `jfrog rt go build go-virtual` works. I had set GOPROXY earlier while going through the `Set Me Up` steps for the repository.
