### ISSUE TITLE
server.upload(uploadSpec) does nothing per example

### ISSUE THREAD

**Issue by mtdeguzis** [jfrog/project-examples#145]
I am not publishing build info, as there are issues I suppose with the object:

```
    //Define artifactory server
    //Definition by node-id does not seem to be working? 403, Jenkins system config is fine
    def artifactory_server = Artifactory.server('artifactory-node1')
    def RPM_ROOT = env.WORKSPACE + "/rpm-repo/simba-hive-jdbc/RPMS"

    // Define upload spec for RPM uploads
    // Does not currently notify you if 0 artifacts were found (BUG?)"
    // "props": "type=rpm"
    echo "Defining upload spec"
    def uploadSpec = """{
      "files": [
        {
          "pattern": "${RPM_ROOT}",
          "target": "rhel-7/",
          "recursive": "true"
        }
     ]
    }"""

```

Upload:
```
        stage('Upload RPM to Artifactory') {
            echo "Verifying existance of file"
            env.RPMPKG = sh(returnStdout: true, script: "find ${RPM_ROOT} -name simba-hive-jdbc*.rpm").trim()
            if(fileExists(env.RPMPKG)) {
                echo "Verified RPM: " + env.RPMPKG
            } else {
                error("RPM File not found! Aborting")
            }
            echo "Uploading RPM package to Artifactory"
            // Set upload
            def buildinfo = artifactory_server.upload(uploadSpec)

```

Jenkins:
```
+ find /opt/jenkins/workspace/operations-testing/simba-hive-jdbc/rpm-repo/simba-hive-jdbc/RPMS -name 'simba-hive-jdbc*.rpm'
[Pipeline] fileExists
[Pipeline] echo
Verified RPM: /opt/jenkins/workspace/operations-testing/simba-hive-jdbc/rpm-repo/simba-hive-jdbc/RPMS/x86_64/simba-hive-jdbc-4.1-1.el7.x86_64.rpm
[Pipeline] echo
Uploading RPM package to Artifactory
[Pipeline] newBuildInfo
[Pipeline] artifactoryUpload
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Cleanup)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
```

**Comment by barbelity** [comment]
@mtdeguzis,

Server definition by id works, the 403 response means 'not permitted' request to Artifactory. It may happen when a certain Artifactory user (can also be anonymous) tries to perform an action without a proper permission. Please elaborate - when exactly are you receiving it?

The plugin does not notify when no artifacts are being uploaded, as happened in your example. I would suggest using a simpler FileSpec definition, just to see that the upload works, and then moving to a more complicated example.

The above pipeline script does not contain a section for uploading build-info. Please refer to our [publishing build-info to Artifactory documentation](https://www.jfrog.com/confluence/display/RTF/Working+With+Pipeline+Jobs+in+Jenkins#WorkingWithPipelineJobsinJenkins-PublishingBuild-InfotoArtifactory).

Please let me know if this answers your questions.

**Comment by mtdeguzis** [comment]
Thank you for the response. Having another member on my team take a look. I'll make sure he's aware of this ticket.

**Comment by djmartin4** [comment]
@barbelity looks like Mike didn't specify a valid pattern. It was set to the folder path. When I added "/*.rpm" to the end it actually attempted to upload the correct rpm. We are having a cert issue now, I think, but since that is outside the scope of this ticket I believe this is solved. Thanks.
