### ISSUE TITLE
Build retention and promotion

### ISSUE THREAD

**Issue by mentaal** [jfrog/project-examples#164]
I can see that there are individual examples of promotion and build retention in the Jenkins declarative pipeline section. 

What I want to do is use build retention in a staging repository and then use `rtAddInteractivePromotion` to promote selected builds to a release repository. 

I have the following questions the documentation for these features is quite terse:

1. Does the selection of what exactly will be deleted as part of build retention depend exclusively on the buildInfo which is uploaded? I don't want to accidentally shoot myself in the foot and accidentally set a build retention policy across the entire repository as opposed to build related files. 
2. Let's say that I promote build X from the staging repo to the release repo with the copy option selected. When the build from staging repo gets deleted, will the buildInfo still be available for the release repo? Or is a new one created as part of the promotion, with the links to the artifacts pointing to the release repository?

**Comment by yahavi** [comment]
1. The build retention deletes only the build and optionally - the build artifacts. Please read our [documentation](https://www.jfrog.com/confluence/display/RTF/Working+With+Pipeline+Jobs+in+Jenkins#WorkingWithPipelineJobsinJenkins-TriggeringBuildRetention) to learn how to do that. 
2. Promotion moves/copies the artifacts from repository A to repository B. It does not create a new build info. Therefore, after deleting the build in Artifactory, you will lose also the published build info.

Hope that it helps.

**Comment by mentaal** [comment]
Yes, it's clear. Thanks.
