### ISSUE TITLE
springboot update,maven deploy artifactory problem

### ISSUE THREAD

**Issue by 15846363412** [jfrog/project-examples#281]

**Comment by 15846363412** [comment]
@yahavi 
hello yahavi,i hava a problem,
when java springboot framework update to 2.4.1,run pipeline  'rtMaven.deployer.deployArtifacts buildInfo', Only a few hundred k of jar packages uploaded to the product library ,Not jar packages with class and lib uploaded , believe it uploaded xxx.jar.original files by mistake 
![image](https://user-images.githubusercontent.com/34851956/118425139-1d53a680-b6fb-11eb-8fe5-0828b6359490.png)
![image](https://user-images.githubusercontent.com/34851956/118425160-25134b00-b6fb-11eb-8fc1-6b127e3b41a8.png)

**Comment by 15846363412** [comment]
@yahavi
version
   jenkins :2.277.1
    Artifactory Plugin: 3.10.6
There is no problem when springboot use 2.0. x, guesses are related to springboot version upgrade in the project

**Comment by eyalbe4** [comment]
@15846363412,
Will you be able to share a sample maven project on GitHub and a pipeline script which demonstrate this issue?

**Comment by 15846363412** [comment]
@eyalbe4 
Some are inconvenient，You can create a new springboot 2.4.x project, then deploy the jar package to the product library through the pipeline, pipeline use the example you've githuab，

**Comment by 15846363412** [comment]
sorry,maven configuration issues
maven configuration issues
![image](https://user-images.githubusercontent.com/34851956/118613599-7aca1f00-b7f1-11eb-88fa-7b11f421ec4f.png)

**Comment by 15846363412** [comment]
sorry,maven configuration issues
maven configuration issues
