### ISSUE TITLE
Unable to pull GO package after publishing

### ISSUE THREAD

**Issue by GaikwadPratik** [jfrog/project-examples#377]
This is more of a question than bug.

Using JFROG Cli, I am publishing my GO package to private instance of artifactory. I am following the step mentioned in the https://github.com/jfrog/project-examples/tree/master/golang-example.

Questions:

1. Is the last step of `Publish the build info to Artifactory` mentioned in the README necessary?
2. Why is the last step trying to upload a json file? How do I view of its contents?
3. what can be value of GO_RESOLVE_REPO in step 2? 
4. When I am executing `go get` on the package, why is it throwing 404 on artifactory.com/api/go/virtual-repo/github.com/fsnotify/fsnotify.mod file? My understanding is, since we are building the package using `jf` in step 3, it should've all the dependencies resolved when it was published to artifactory?

Please let me know if you need any information from me. If you need any trace logs, please let me know how to obtain them.

**Comment by yonarbel** [comment]
Greetings,

Regarding point 1, while publishing build information is not obligatory, it can prove beneficial for future reference, aiding in identifying distinctions among other published builds. For detailed insights into builds, kindly refer to the following link: https://www.buildinfo.org/#

Point 2 emphasizes that the JSON serves as the actual build information.
You can view its content under “builds” tab in the UI or via a REST 
As for point 3, the choice of repository type depends on your requirements. If resource retrieval from a remote repository or registry is essential, a remote repository is advisable. Alternatively, for internal packages, especially private ones, a local repository is recommended. A viable approach is to employ a virtual repository, enabling a centralized point capable of fetching both internal and external packages.

In point 4, have you appropriately configured your remote repository on the virtual repository?

Best regards.

**Comment by GaikwadPratik** [comment]
@yonarbel ,

Thank you for responding. The answers were somewhat helpful.
Regrading your question about point 4, I am not sure what would be correct remote repository URL, I tried several. I am reaching out to engineering team to get the answer. 

Although this raises another question. Is there a way to resolve all dependencies locally and then use those inside package(zip) file before publishing to artifactory? I am not asking about or looking for `vendor`ing. In fact, whole idea is to avoid that.
